DROP TABLE IF EXISTS TWEETS;

CREATE TABLE TWEETS(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  text VARCHAR(280) NOT NULL,
  location VARCHAR(250) DEFAULT NULL,
  validated BOOLEAN DEFAULT FALSE
);
